name: 'Go cover diff'
description: 'Action that comments PR with test coverage changes summary.'
branding:
  icon: 'eye'
  color: 'blue'
inputs:
  base:
    description: "Base branch for comparison."
    required: false
    default: "main"
  # TODO add a change threshold to fail the PR if we go below threshold
runs:
  using: 'composite'
  steps:
    - name: 'Checkout After'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: '1'
    - name: 'Setup Golang'
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: 'Generate coverage After'
      shell: bash
      run: |
        go test -cover ./... |\
          grep -v "\[no test files\]" |\
          grep -v "\[no statements\]" |\
          grep "^\(ok\|FAIL\).*" |\
          awk '{printf "%s %d\n", $2, $5}' > after.cover
    - name: 'Checkout Before'
      uses: actions/checkout@v3
      with:
        path: base
        ref: ${{ github.event.pull_request.base.sha }}
        fetch-depth: '1'
    - name: 'Generate coverage Before'
      working-directory: base
      shell: bash
      run: |
        go test -cover ./... |\
          grep -v "\[no test files\]" |\
          grep -v "\[no statements\]" |\
          grep "^\(ok\|FAIL\).*" |\
          awk '{printf "%s %d\n", $2, $5}' > before.cover
    - name: 'Copy Before'
      shell: bash
      run: cp base/before.cover before.cover
    - name: 'Generate diff'
      shell: bash
      run: |
        #!/bin/bash
        set -oe pipefail

        declare -A coverage_before
        while read -r pkg x; do
          coverage_before["$pkg"]="$x"
        done < "before.cover"

        declare -A coverage_after
        while read -r pkg x; do
          coverage_after["$pkg"]="$x"
        done < "after.cover"

        declare -A all_pkgs
        for pkg in "${!coverage_before[@]}"; do
          all_pkgs["$pkg"]=1
        done
        for pkg in "${!coverage_after[@]}"; do
          all_pkgs["$pkg"]=1
        done

        > diff_raw
        for pkg in "${!all_pkgs[@]}"; do
          before="${coverage_before[$pkg]}"
          after="${coverage_after[$pkg]}"

          if [[ -z "$before" ]]; then
            echo "| $pkg | - | ${after}% | :heavy_check_mark: |" >> diff_raw
            continue
          elif [[ -z "$after" ]]; then
            echo "| $pkg | ${before}% | - | :question: |" >> diff_raw
            continue
          fi

          if [[ "$before" -gt "$after" ]]; then
            echo "| $pkg | ${before}% | ${after}% | :x: |" >> diff_raw
          else
            echo "| $pkg | ${before}% | ${after}% | :heavy_check_mark: |" >> diff_raw
          fi
        done

        echo "Test coverage changes:" > diff
        echo "| Package | Before | After | Diff |" >> diff
        echo "|-|-|-|-|" >> diff
        cat diff_raw | sort >> diff

        cat diff
    - name: 'Comment PR'
      uses: thollander/actions-comment-pull-request@v2
      with:
        #GITHUB_TOKEN: ${{ secrets.COMMENTER_TOKEN }}
        pr_number: ${{ github.event.pull_request.number }}
        # need the PR number argument because after checkingout B we are no longer on the right branch
        comment_tag: Coverdiff
        filePath: diff
