name: 'Go cover diff'
description: 'Action that comments PR with test coverage changes summary.'
branding:
  icon: 'eye'
  color: 'blue'
inputs:
  base:
    description: "Base branch for comparison."
    required: false
    default: "main"
  # TODO add a change threshold to fail the PR if we go below threshold
runs:
  using: 'composite'
  steps:
    - name: 'Setup Golang'
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: 'Checkout After'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: '1'
    - name: 'Generate coverage After'
      shell: bash
      run: |
        go test -cover ./... |\
          grep -v "no test files" |\
          grep -v "\[no statements\]" |\
          sed 's/^ok//' | sed 's/coverage://' |\
          sed 's/(cached)//' |\
          awk '{printf "%s %d\n", $1, $2}' > after.cover
    - name: 'Checkout Before'
      uses: actions/checkout@v3
      with:
        path: base
        ref: ${{ github.event.pull_request.base.sha }}
        fetch-depth: '1'
    - name: 'Generate coverage Before'
      working-directory: base
      shell: bash
      run: |
        go test -cover ./... |\
          grep -v "no test files" |\
          grep -v "\[no statements\]" |\
          sed 's/^ok//' | sed 's/coverage://' |\
          sed 's/(cached)//' |\
          awk '{printf "%s %d\n", $1, $2}' > before.cover
    - name: 'Generate diff'
      shell: bash
      run: ./run.sh
    - name: 'Comment PR'
      uses: thollander/actions-comment-pull-request@v2
      with:
        #GITHUB_TOKEN: ${{ secrets.COMMENTER_TOKEN }}
        pr_number: ${{ github.event.pull_request.number }}
        # need the PR number argument because after checkingout B we are no longer on the right branch
        comment_tag: Coverdiff
        filePath: diff
