name: 'Go cover diff'
description: 'Action that comments PR with test coverage changes summary.'
branding:
  icon: 'eye'
  color: 'blue'
inputs:
  base:
    description: "Base branch for comparison."
    required: false
    default: "main"
  # TODO add a change threshold to fail the PR if we go below threshold
runs:
  using: 'composite'
  steps:
    - name: 'Checkout A'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: '1'
    - name: 'Setup Golang'
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
    - name: 'Generate coverage A'
      shell: bash
      run: paste go.mod go.sum
    - name: 'Generate coverage A'
      shell: bash
      run: go test -cover ./... | grep -v "no test files" | awk '{printf "%s a %d\n", $2, $5}' | sed -e 's/%//' > a.cover
    - name: 'Checkout B'
      uses: actions/checkout@v3
      with:
        path: base
        ref: ${{ github.event.pull_request.base.sha }}
        fetch-depth: '1'
    - name: 'Generate coverage B'
      working-directory: base
      shell: bash
      run: go test -cover ./... | grep -v "no test files" | awk '{printf "%s b %d\n", $2, $5}' | sed -e 's/%//' > b.cover
    - name: 'Generate diff'
      shell: bash
      run: |
        echo "Test coverage changes:" > diff
        echo "| Package | Before | After | Diff |" >> diff
        echo "|-|-|-|-|" >> diff
        cat a.cover > sum.cover
        cat base/b.cover >> sum.cover
        cat sum.cover | sort | uniq | awk '{pkg=$1; side=$2; x=$3;
          if (side == "a") a=x;
          if (side == "b") b=x;
          if (a != "" && b != "") {
            if (a < b) {printf "| %s | %d% | %d% | :heavy_check_mark: |\n", pkg,a,b};
            if (a > b) {printf "| %s | %d% | %d% | :x:                |\n", pkg,a,b};
            a=""; b=""
          }
          }' >> diff
        cat diff
    - name: 'Comment PR'
      uses: thollander/actions-comment-pull-request@v2
      with:
        #GITHUB_TOKEN: ${{ secrets.COMMENTER_TOKEN }}
        pr_number: ${{ github.event.pull_request.number }}
        # need the PR number argument because after checkingout B we are no longer on the right branch
        comment_tag: Coverdiff
        filePath: diff
